services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spark-net

  spark:
    build: ./spark
    container_name: tarea2spark
    user: root
    ports:
      - "4040:4040"
    depends_on:
      - mysql
    volumes:
       - ./spark:/opt/spark/work-dir
    environment:
      - SPARK_HOME=/opt/spark
    command: >
      /opt/spark/bin/spark-submit
      --jars /opt/spark/jars/mysql-connector-j-8.0.33.jar
      /opt/spark/work-dir/job.py
    networks:
      - spark-net

networks:
  spark-net:
